/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reto2;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juancparra
 */
public class Menu extends javax.swing.JFrame {
    
    DefaultTableModel modelo, modelo1, modelo2, modelo3, modelo4;

    /**
     * Creates new form Menu
     */
    public Menu() {
        
        initComponents();
        
        String[] titulos = {"Nombre", "Id", "Municipio", "Tipo de cuerpo de agua", "Tipo de agua", "IRCA"};
        String[] tCuerpos = {"Cuerpos Agua"};
        String[] tMenosBajo = {"Numero cuerpos irca inferior"};
        String[] tBajo = {"Cuerpos irca bajo"};
        String[] tMax = {"Cuerpos maximo irca"};
        
        
        modelo = new DefaultTableModel(null, titulos);
        modelo2 = new DefaultTableModel(null, tMenosBajo);
        modelo3 = new DefaultTableModel(null, tBajo);
        modelo4 = new DefaultTableModel(null, tMax);
        
        queryTable.setModel(modelo);
        jTable1.setModel(modelo2);
        jTable2.setModel(modelo3);
        jTable3.setModel(modelo4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        createPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        municipioField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cuerpoField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        ircaField = new javax.swing.JTextField();
        ingresarButton = new javax.swing.JButton();
        processPanel = new javax.swing.JPanel();
        obtenerButton = new javax.swing.JButton();
        procesarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        editPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        idSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nameField2 = new javax.swing.JTextField();
        municipioField2 = new javax.swing.JTextField();
        typeField2 = new javax.swing.JTextField();
        cuerpoField2 = new javax.swing.JTextField();
        ircaField2 = new javax.swing.JTextField();
        editarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jLabel5.setText("Municipio");

        municipioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de cuerpo de agua");

        jLabel7.setText("Tipo de agua");

        jLabel8.setText("IRCA");

        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });

        ingresarButton.setText("Ingresar");
        ingresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresarButton)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(createPanelLayout.createSequentialGroup()
                                .addComponent(cuerpoField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(createPanelLayout.createSequentialGroup()
                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel7))
                                    .addGroup(createPanelLayout.createSequentialGroup()
                                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(41, 41, 41)
                                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))))
                                .addGap(36, 36, 36)))
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(ircaField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipioField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuerpoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ircaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(ingresarButton)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar", createPanel);

        obtenerButton.setText("Obtener Datos");
        obtenerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerButtonActionPerformed(evt);
            }
        });

        procesarButton.setText("Procesar Datos");
        procesarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarButtonActionPerformed(evt);
            }
        });

        queryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(queryTable);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout processPanelLayout = new javax.swing.GroupLayout(processPanel);
        processPanel.setLayout(processPanelLayout);
        processPanelLayout.setHorizontalGroup(
            processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processPanelLayout.createSequentialGroup()
                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(processPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(processPanelLayout.createSequentialGroup()
                        .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(processPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(processPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(procesarButton)
                                    .addComponent(obtenerButton))))
                        .addGap(106, 106, 106)
                        .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        processPanelLayout.setVerticalGroup(
            processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(procesarButton)
                        .addGap(72, 72, 72))
                    .addGroup(processPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(processPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(obtenerButton)
                                .addGap(113, 113, 113))
                            .addGroup(processPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jTabbedPane1.addTab("Procesar datos", processPanel);

        jLabel3.setText("ID");

        idSearchField.setToolTipText("");
        idSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSearchFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultados de la busqueda");

        jLabel9.setText("Nombre");

        idField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField2ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID");

        jLabel11.setText("Municipio");

        jLabel12.setText("Tipo de cuerpo de agua");

        jLabel13.setText("Tipo de agua");

        jLabel14.setText("IRCA");

        nameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField2ActionPerformed(evt);
            }
        });

        municipioField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioField2ActionPerformed(evt);
            }
        });

        typeField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeField2ActionPerformed(evt);
            }
        });

        cuerpoField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuerpoField2ActionPerformed(evt);
            }
        });

        ircaField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ircaField2ActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(editarButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(idSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarButton))
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nameField2)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cuerpoField2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(36, 36, 36)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addGroup(editPanelLayout.createSequentialGroup()
                                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(idField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(typeField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(municipioField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel14)
                                            .addComponent(ircaField2))))))
                        .addContainerGap(135, Short.MAX_VALUE))))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipioField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ircaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuerpoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(eliminarButton))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar/Eliminar", editPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        mostrarDato();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        borrarDato();
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
        editarDato();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void ircaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ircaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ircaField2ActionPerformed

    private void cuerpoField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuerpoField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuerpoField2ActionPerformed

    private void typeField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeField2ActionPerformed

    private void municipioField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioField2ActionPerformed

    private void nameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField2ActionPerformed

    private void idField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField2ActionPerformed

    private void idSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSearchFieldActionPerformed

    private void procesarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarButtonActionPerformed
        // TODO add your handling code here:
        mostrarDatos1();
        mostrarDatos2();
        mostrarDatos3();
        mostrarDatos4();
    }//GEN-LAST:event_procesarButtonActionPerformed

    private void obtenerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerButtonActionPerformed
        // TODO add your handling code here:
        mostrarDatos();
    }//GEN-LAST:event_obtenerButtonActionPerformed

    private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed

        CuerpoDeAgua oCuerpo = recuperarDatosGUI();
        String strSentenciaInsert = String.format("insert into cuerpoAgua VALUES ('%s', %s, '%s', '%s', '%s', %s)",
            oCuerpo.getNombre(),
            oCuerpo.getId(),
            oCuerpo.getMunicipio(),
            oCuerpo.getTipoCuerpo(),
            oCuerpo.getTipoAgua(),
            oCuerpo.getIrca());

        conexion objConexion = new conexion();
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
    }//GEN-LAST:event_ingresarButtonActionPerformed

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void municipioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    public void mostrarDato() {
        
        conexion objConexion = new conexion();
        
        String strSentenciaSelect = String.format("select * from cuerpoAgua where id = %s", idSearchField.getText());
                
        try {
            
            ResultSet resultado = objConexion.consultarRegistros(strSentenciaSelect);
            
            nameField2.setText(resultado.getString("nombre"));
            idField2.setText(resultado.getString("id"));
            municipioField2.setText(resultado.getString("municipio"));
            cuerpoField2.setText(resultado.getString("cuerpo"));
            typeField2.setText(resultado.getString("tipo"));
            ircaField2.setText(resultado.getString("irca"));
            
        }
        
        catch (Exception e) {
            System.out.println(e);
            
        }
    }
        
        
    public void mostrarDatos() {
        
        conexion objConexion = new conexion();
        String[] titulos = {"Nombre", "Id", "Municipio", "Tipo de cuerpo de agua", "Tipo de agua", "IRCA"};
        modelo = new DefaultTableModel(null, titulos);
        queryTable.setModel(modelo);
        
        try {
            
            ResultSet resultado = objConexion.consultarRegistros("select * from cuerpoAgua");
            
            while (resultado.next()) {
                
                
                Object[] oCuerposAgua = {resultado.getString("nombre"), 
                                        resultado.getString("id"),
                                        resultado.getString("municipio"),
                                        resultado.getString("cuerpo"),
                                        resultado.getString("tipo"),
                                        resultado.getString("irca")
                };
                
                
                modelo.addRow(oCuerposAgua);
            }
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
        
        try {
            objConexion.conn.close();
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
    }
        
    public void mostrarDatos1() {
        
        conexion objConexion = new conexion();
        String[] tCuerpos = {"Cuerpos Agua"};
        modelo = new DefaultTableModel(null, tCuerpos);
        queryTable.setModel(modelo);
        
        try {
            
            ResultSet resultado = objConexion.consultarRegistros("select nombre from cuerpoAgua");
            
            while (resultado.next()) {
                
                
                Object[] oCuerposAgua = {resultado.getString("nombre")
                };
                
                
                modelo.addRow(oCuerposAgua);
            }
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
        
        try {
            objConexion.conn.close();
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public void mostrarDatos2() {
        
        conexion objConexion = new conexion();
        String[] tMenosBajo = {"Numero cuerpos irca inferior"};
        modelo = new DefaultTableModel(null, tMenosBajo);
        jTable1.setModel(modelo);
        
        try {
            
            ResultSet resultado = objConexion.consultarRegistros("select count(*) as c from cuerpoAgua where irca < 14");
            
            while (resultado.next()) {
                
                
                Object[] oCuerposAgua = {resultado.getString("c")
                };
                
                
                modelo.addRow(oCuerposAgua);
            }
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
        
        try {
            objConexion.conn.close();
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public void mostrarDatos3() {
        
        conexion objConexion = new conexion();
        String[] tBajo = {"Cuerpos irca bajo"};
        modelo = new DefaultTableModel(null, tBajo);
        jTable2.setModel(modelo);
        
        try {
            
            ResultSet resultado = objConexion.consultarRegistros("select nombre from cuerpoAgua where irca < 14 and irca > 5");
            
            while (resultado.next()) {
                
                
                Object[] oCuerposAgua = {resultado.getString("nombre")
                };
                
                
                modelo.addRow(oCuerposAgua);
            }
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
        
        try {
            objConexion.conn.close();
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public void mostrarDatos4() {
        
        conexion objConexion = new conexion();
        String[] tMax = {"Cuerpos maximo irca id", "Nombre"};
        modelo = new DefaultTableModel(null, tMax);
        jTable3.setModel(modelo);
        
        try {
            
            ResultSet resultado = objConexion.consultarRegistros("select id, nombre from cuerpoAgua where irca = (select max(irca) from cuerpoAgua)");
            
            while (resultado.next()) {
                
                
                Object[] oCuerposAgua = {resultado.getString("id"),
                                         resultado.getString("nombre")};
                
                
                modelo.addRow(oCuerposAgua);
            }
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
        
        try {
            objConexion.conn.close();
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public void borrarDato() {
        
        conexion objConexion = new conexion();
        String strSentenciaDelete = String.format("delete * from cuerpoAgua where id = %s", idField2.getText());
        
        try {
            objConexion.ejecutarSentenciaSQL(strSentenciaDelete);
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
    }
    
    public void editarDato() {
        
        conexion objConexion = new conexion();
        String strSentenciaDelete = String.format("update cuerpoAgua set nombre = '%s', municipio = '%s', cuerpo = '%s', tipo = '%s', irca = %s where id = %s", 
                                                nameField2.getText(),
                                                municipioField2.getText(),
                                                cuerpoField2.getText(),
                                                typeField2.getText(),
                                                ircaField2.getText(),
                                                idField2.getText());
        
        try {
            objConexion.ejecutarSentenciaSQL(strSentenciaDelete);
        }
        catch (Exception e) {
            System.out.println(e);
            
        }
        
        try {
            objConexion.conn.close();
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
        
    }
        
            
    public CuerpoDeAgua recuperarDatosGUI() {
        
        CuerpoDeAgua oCuerpo = new CuerpoDeAgua();
        
        double id = (idField.getText().isEmpty())?0.0: Double.parseDouble(idField.getText());
        double irca = Double.parseDouble(ircaField.getText());
        oCuerpo.setId(id);
        oCuerpo.setIrca(irca);
        oCuerpo.setNombre(nameField.getText());
        oCuerpo.setMunicipio(municipioField.getText());
        oCuerpo.setTipoCuerpo(cuerpoField.getText());
        oCuerpo.setTipoAgua(typeField.getText());
        
        return oCuerpo;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JPanel createPanel;
    private javax.swing.JTextField cuerpoField;
    private javax.swing.JTextField cuerpoField2;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField2;
    private javax.swing.JTextField idSearchField;
    private javax.swing.JButton ingresarButton;
    private javax.swing.JTextField ircaField;
    private javax.swing.JTextField ircaField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField municipioField;
    private javax.swing.JTextField municipioField2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField2;
    private javax.swing.JButton obtenerButton;
    private javax.swing.JButton procesarButton;
    private javax.swing.JPanel processPanel;
    private javax.swing.JTable queryTable;
    private javax.swing.JTextField typeField;
    private javax.swing.JTextField typeField2;
    // End of variables declaration//GEN-END:variables
}
